dist: trusty
language: cpp
compiler:
  - gcc
env:
  global:
    - RUN_TESTS=true

os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt install cmake
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

    packages:
      - gcc-6
      - g++-6


script:
  - mkdir bin
  - cd bin
  - /usr/local/bin/cmake ..
  - make argParser_Test
  - ctest

notifications:
  email: false
