title: C++ Argument-Parser
description: Easy to use C++ argument parsing library. Features : generating help messages, bash auto completion, callback function or lambda for each argument.
url: https://diridari.github.io/CPP-Argument-Parser/ 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
