# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/basto/git/CPP-Argument-Parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/basto/git/CPP-Argument-Parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basto/git/CPP-Argument-Parser/CMakeFiles /home/basto/git/CPP-Argument-Parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basto/git/CPP-Argument-Parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPPArgvParsLib

# Build rule for target.
CPPArgvParsLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPPArgvParsLib
.PHONY : CPPArgvParsLib

# fast build rule for target.
CPPArgvParsLib/fast:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/build
.PHONY : CPPArgvParsLib/fast

#=============================================================================
# Target rules for targets named argParser_Test

# Build rule for target.
argParser_Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argParser_Test
.PHONY : argParser_Test

# fast build rule for target.
argParser_Test/fast:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/build
.PHONY : argParser_Test/fast

#=============================================================================
# Target rules for targets named simpleExample

# Build rule for target.
simpleExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleExample
.PHONY : simpleExample

# fast build rule for target.
simpleExample/fast:
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/build
.PHONY : simpleExample/fast

#=============================================================================
# Target rules for targets named extendedExmple

# Build rule for target.
extendedExmple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extendedExmple
.PHONY : extendedExmple

# fast build rule for target.
extendedExmple/fast:
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/build
.PHONY : extendedExmple/fast

exampleMainExtended.o: exampleMainExtended.cpp.o

.PHONY : exampleMainExtended.o

# target to build an object file
exampleMainExtended.cpp.o:
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/exampleMainExtended.cpp.o
.PHONY : exampleMainExtended.cpp.o

exampleMainExtended.i: exampleMainExtended.cpp.i

.PHONY : exampleMainExtended.i

# target to preprocess a source file
exampleMainExtended.cpp.i:
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/exampleMainExtended.cpp.i
.PHONY : exampleMainExtended.cpp.i

exampleMainExtended.s: exampleMainExtended.cpp.s

.PHONY : exampleMainExtended.s

# target to generate assembly for a file
exampleMainExtended.cpp.s:
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/exampleMainExtended.cpp.s
.PHONY : exampleMainExtended.cpp.s

exampleMainSimple.o: exampleMainSimple.cpp.o

.PHONY : exampleMainSimple.o

# target to build an object file
exampleMainSimple.cpp.o:
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/exampleMainSimple.cpp.o
.PHONY : exampleMainSimple.cpp.o

exampleMainSimple.i: exampleMainSimple.cpp.i

.PHONY : exampleMainSimple.i

# target to preprocess a source file
exampleMainSimple.cpp.i:
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/exampleMainSimple.cpp.i
.PHONY : exampleMainSimple.cpp.i

exampleMainSimple.s: exampleMainSimple.cpp.s

.PHONY : exampleMainSimple.s

# target to generate assembly for a file
exampleMainSimple.cpp.s:
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/exampleMainSimple.cpp.s
.PHONY : exampleMainSimple.cpp.s

src/argParserAdvancedConfiguration.o: src/argParserAdvancedConfiguration.cpp.o

.PHONY : src/argParserAdvancedConfiguration.o

# target to build an object file
src/argParserAdvancedConfiguration.cpp.o:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argParserAdvancedConfiguration.cpp.o
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argParserAdvancedConfiguration.cpp.o
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argParserAdvancedConfiguration.cpp.o
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argParserAdvancedConfiguration.cpp.o
.PHONY : src/argParserAdvancedConfiguration.cpp.o

src/argParserAdvancedConfiguration.i: src/argParserAdvancedConfiguration.cpp.i

.PHONY : src/argParserAdvancedConfiguration.i

# target to preprocess a source file
src/argParserAdvancedConfiguration.cpp.i:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argParserAdvancedConfiguration.cpp.i
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argParserAdvancedConfiguration.cpp.i
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argParserAdvancedConfiguration.cpp.i
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argParserAdvancedConfiguration.cpp.i
.PHONY : src/argParserAdvancedConfiguration.cpp.i

src/argParserAdvancedConfiguration.s: src/argParserAdvancedConfiguration.cpp.s

.PHONY : src/argParserAdvancedConfiguration.s

# target to generate assembly for a file
src/argParserAdvancedConfiguration.cpp.s:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argParserAdvancedConfiguration.cpp.s
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argParserAdvancedConfiguration.cpp.s
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argParserAdvancedConfiguration.cpp.s
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argParserAdvancedConfiguration.cpp.s
.PHONY : src/argParserAdvancedConfiguration.cpp.s

src/argvParser.o: src/argvParser.cpp.o

.PHONY : src/argvParser.o

# target to build an object file
src/argvParser.cpp.o:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argvParser.cpp.o
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argvParser.cpp.o
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argvParser.cpp.o
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argvParser.cpp.o
.PHONY : src/argvParser.cpp.o

src/argvParser.i: src/argvParser.cpp.i

.PHONY : src/argvParser.i

# target to preprocess a source file
src/argvParser.cpp.i:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argvParser.cpp.i
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argvParser.cpp.i
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argvParser.cpp.i
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argvParser.cpp.i
.PHONY : src/argvParser.cpp.i

src/argvParser.s: src/argvParser.cpp.s

.PHONY : src/argvParser.s

# target to generate assembly for a file
src/argvParser.cpp.s:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/argvParser.cpp.s
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/argvParser.cpp.s
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/argvParser.cpp.s
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/argvParser.cpp.s
.PHONY : src/argvParser.cpp.s

src/configFileReader.o: src/configFileReader.cpp.o

.PHONY : src/configFileReader.o

# target to build an object file
src/configFileReader.cpp.o:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/configFileReader.cpp.o
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/configFileReader.cpp.o
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/configFileReader.cpp.o
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/configFileReader.cpp.o
.PHONY : src/configFileReader.cpp.o

src/configFileReader.i: src/configFileReader.cpp.i

.PHONY : src/configFileReader.i

# target to preprocess a source file
src/configFileReader.cpp.i:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/configFileReader.cpp.i
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/configFileReader.cpp.i
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/configFileReader.cpp.i
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/configFileReader.cpp.i
.PHONY : src/configFileReader.cpp.i

src/configFileReader.s: src/configFileReader.cpp.s

.PHONY : src/configFileReader.s

# target to generate assembly for a file
src/configFileReader.cpp.s:
	$(MAKE) -f CMakeFiles/CPPArgvParsLib.dir/build.make CMakeFiles/CPPArgvParsLib.dir/src/configFileReader.cpp.s
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/src/configFileReader.cpp.s
	$(MAKE) -f CMakeFiles/simpleExample.dir/build.make CMakeFiles/simpleExample.dir/src/configFileReader.cpp.s
	$(MAKE) -f CMakeFiles/extendedExmple.dir/build.make CMakeFiles/extendedExmple.dir/src/configFileReader.cpp.s
.PHONY : src/configFileReader.cpp.s

tests/advancedConfigurationTest.o: tests/advancedConfigurationTest.cpp.o

.PHONY : tests/advancedConfigurationTest.o

# target to build an object file
tests/advancedConfigurationTest.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/advancedConfigurationTest.cpp.o
.PHONY : tests/advancedConfigurationTest.cpp.o

tests/advancedConfigurationTest.i: tests/advancedConfigurationTest.cpp.i

.PHONY : tests/advancedConfigurationTest.i

# target to preprocess a source file
tests/advancedConfigurationTest.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/advancedConfigurationTest.cpp.i
.PHONY : tests/advancedConfigurationTest.cpp.i

tests/advancedConfigurationTest.s: tests/advancedConfigurationTest.cpp.s

.PHONY : tests/advancedConfigurationTest.s

# target to generate assembly for a file
tests/advancedConfigurationTest.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/advancedConfigurationTest.cpp.s
.PHONY : tests/advancedConfigurationTest.cpp.s

tests/argvParserTest.o: tests/argvParserTest.cpp.o

.PHONY : tests/argvParserTest.o

# target to build an object file
tests/argvParserTest.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/argvParserTest.cpp.o
.PHONY : tests/argvParserTest.cpp.o

tests/argvParserTest.i: tests/argvParserTest.cpp.i

.PHONY : tests/argvParserTest.i

# target to preprocess a source file
tests/argvParserTest.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/argvParserTest.cpp.i
.PHONY : tests/argvParserTest.cpp.i

tests/argvParserTest.s: tests/argvParserTest.cpp.s

.PHONY : tests/argvParserTest.s

# target to generate assembly for a file
tests/argvParserTest.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/argvParserTest.cpp.s
.PHONY : tests/argvParserTest.cpp.s

tests/configReaderTest.o: tests/configReaderTest.cpp.o

.PHONY : tests/configReaderTest.o

# target to build an object file
tests/configReaderTest.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/configReaderTest.cpp.o
.PHONY : tests/configReaderTest.cpp.o

tests/configReaderTest.i: tests/configReaderTest.cpp.i

.PHONY : tests/configReaderTest.i

# target to preprocess a source file
tests/configReaderTest.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/configReaderTest.cpp.i
.PHONY : tests/configReaderTest.cpp.i

tests/configReaderTest.s: tests/configReaderTest.cpp.s

.PHONY : tests/configReaderTest.s

# target to generate assembly for a file
tests/configReaderTest.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/configReaderTest.cpp.s
.PHONY : tests/configReaderTest.cpp.s

tests/definedNumberOfArgs.o: tests/definedNumberOfArgs.cpp.o

.PHONY : tests/definedNumberOfArgs.o

# target to build an object file
tests/definedNumberOfArgs.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/definedNumberOfArgs.cpp.o
.PHONY : tests/definedNumberOfArgs.cpp.o

tests/definedNumberOfArgs.i: tests/definedNumberOfArgs.cpp.i

.PHONY : tests/definedNumberOfArgs.i

# target to preprocess a source file
tests/definedNumberOfArgs.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/definedNumberOfArgs.cpp.i
.PHONY : tests/definedNumberOfArgs.cpp.i

tests/definedNumberOfArgs.s: tests/definedNumberOfArgs.cpp.s

.PHONY : tests/definedNumberOfArgs.s

# target to generate assembly for a file
tests/definedNumberOfArgs.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/definedNumberOfArgs.cpp.s
.PHONY : tests/definedNumberOfArgs.cpp.s

tests/exampleTest.o: tests/exampleTest.cpp.o

.PHONY : tests/exampleTest.o

# target to build an object file
tests/exampleTest.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/exampleTest.cpp.o
.PHONY : tests/exampleTest.cpp.o

tests/exampleTest.i: tests/exampleTest.cpp.i

.PHONY : tests/exampleTest.i

# target to preprocess a source file
tests/exampleTest.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/exampleTest.cpp.i
.PHONY : tests/exampleTest.cpp.i

tests/exampleTest.s: tests/exampleTest.cpp.s

.PHONY : tests/exampleTest.s

# target to generate assembly for a file
tests/exampleTest.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/exampleTest.cpp.s
.PHONY : tests/exampleTest.cpp.s

tests/lambdaTest.o: tests/lambdaTest.cpp.o

.PHONY : tests/lambdaTest.o

# target to build an object file
tests/lambdaTest.cpp.o:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/lambdaTest.cpp.o
.PHONY : tests/lambdaTest.cpp.o

tests/lambdaTest.i: tests/lambdaTest.cpp.i

.PHONY : tests/lambdaTest.i

# target to preprocess a source file
tests/lambdaTest.cpp.i:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/lambdaTest.cpp.i
.PHONY : tests/lambdaTest.cpp.i

tests/lambdaTest.s: tests/lambdaTest.cpp.s

.PHONY : tests/lambdaTest.s

# target to generate assembly for a file
tests/lambdaTest.cpp.s:
	$(MAKE) -f CMakeFiles/argParser_Test.dir/build.make CMakeFiles/argParser_Test.dir/tests/lambdaTest.cpp.s
.PHONY : tests/lambdaTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... CPPArgvParsLib"
	@echo "... argParser_Test"
	@echo "... simpleExample"
	@echo "... extendedExmple"
	@echo "... exampleMainExtended.o"
	@echo "... exampleMainExtended.i"
	@echo "... exampleMainExtended.s"
	@echo "... exampleMainSimple.o"
	@echo "... exampleMainSimple.i"
	@echo "... exampleMainSimple.s"
	@echo "... src/argParserAdvancedConfiguration.o"
	@echo "... src/argParserAdvancedConfiguration.i"
	@echo "... src/argParserAdvancedConfiguration.s"
	@echo "... src/argvParser.o"
	@echo "... src/argvParser.i"
	@echo "... src/argvParser.s"
	@echo "... src/configFileReader.o"
	@echo "... src/configFileReader.i"
	@echo "... src/configFileReader.s"
	@echo "... tests/advancedConfigurationTest.o"
	@echo "... tests/advancedConfigurationTest.i"
	@echo "... tests/advancedConfigurationTest.s"
	@echo "... tests/argvParserTest.o"
	@echo "... tests/argvParserTest.i"
	@echo "... tests/argvParserTest.s"
	@echo "... tests/configReaderTest.o"
	@echo "... tests/configReaderTest.i"
	@echo "... tests/configReaderTest.s"
	@echo "... tests/definedNumberOfArgs.o"
	@echo "... tests/definedNumberOfArgs.i"
	@echo "... tests/definedNumberOfArgs.s"
	@echo "... tests/exampleTest.o"
	@echo "... tests/exampleTest.i"
	@echo "... tests/exampleTest.s"
	@echo "... tests/lambdaTest.o"
	@echo "... tests/lambdaTest.i"
	@echo "... tests/lambdaTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

